resolver: lts-7.8

packages:
- '.'
- location:
    git:    https://github.com/llvm-hs/llvm-hs.git
    commit: 6aa16d9bb7d29639d3a9e667227e8819f7d8fb51
  extra-dep: true
  subdirs:
    - 'llvm-hs'
    - 'llvm-hs-pure'

flags:
  llvm-hs:
    shared-llvm: true

extra-package-dbs: []
